# Build stage
FROM openjdk:11 as build-stage

WORKDIR /app

COPY . .

RUN ./gradlew clean shadowJar

# Create runnable image
FROM openjdk:11

EXPOSE 8080 8081

COPY --from=build-stage /app/build/libs/authentication-service.jar /authentication-service/authentication-service.jar

CMD ["java", "-jar", "/authentication-service/authentication-service.jar", "server"]